# Generated by Django 4.1.3 on 2022-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
